### ISSUE TITLE
Missing tables directory?

### ISSUE THREAD

**Issue by mp15** [DKMS-LSL/typeloader#3]
When attempting to create an initial user I get the following error:

```
INFO [2018-10-23 14:14:27] - Creating new user...
DEBUG [2018-10-23 14:14:27] - Creating user dir under /Users/mp15/dev/hla/p1_arrow_analysis/typeloader_data/mp15
INFO [2018-10-23 14:14:27] - Establishing user settings for new user mp15...
INFO [2018-10-23 14:14:27] - Loading base config from /Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/config_base.ini...
DEBUG [2018-10-23 14:14:27] - Preparing user dir under /Users/mp15/dev/hla/p1_arrow_analysis/typeloader_data/mp15
INFO [2018-10-23 14:14:27] - 	=> Done!
INFO [2018-10-23 14:14:27] - Loading user settings...
INFO [2018-10-23 14:14:27] - Loading base config from /Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/config_base.ini...
INFO [2018-10-23 14:14:27] - 	=>Success
INFO [2018-10-23 14:14:27] - Creating new user space...
INFO [2018-10-23 14:14:27] - Creating empty database...
INFO [2018-10-23 14:14:27] - Creating empty tables for new user...
DEBUG [2018-10-23 14:14:27] - Opening connection to /Users/mp15/dev/hla/p1_arrow_analysis/typeloader_data/mp15/data.db...
DEBUG [2018-10-23 14:14:27] - 	=> Connection opened successfully.
INFO [2018-10-23 14:14:27] - Creating tables...
ERROR [2018-10-23 14:14:27] - [Errno 2] No such file or directory: 'tables'
ERROR [2018-10-23 14:14:27] - [Errno 2] No such file or directory: 'tables'
Traceback (most recent call last):
  File "/Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/GUI_login.py", line 251, in handle_new_user
    self.short, self.email, self.address, self.log)
  File "/Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/GUI_login.py", line 462, in create_user_space
    db_internal.make_clean_db(settings_dic["db_file"], log)
  File "/Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/db_internal.py", line 367, in make_clean_db
    make_tables(cursor, log, tables, insert_dummy_data = False)
  File "/Users/mp15/dev/hla/p1_arrow_analysis/typeloader/src/db_internal.py", line 300, in make_tables
    for myfile in os.listdir(tables_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'tables'
```

Are we missing a tables directory in the GitHub package?

**Comment by bmschoene** [comment]
Yes. This and the previous issue (and a number of others) will be fixed in the next release, later this week. Sorry for the inconvenience!

**Comment by bmschoene** [comment]
The new release 2.1.0 should fix this. Please try it out and let us know of any further issues?
